plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name = "Quilt"
        url = "https://maven.quiltmc.org/repository/release"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    runtimeOnly "maven.modrinth:sodium:${sodium_version}"
    runtimeOnly "maven.modrinth:iris:${iris_version}"
    runtimeOnly "maven.modrinth:structurify:${structurify_version}"
    runtimeOnly "maven.modrinth:yacl:${yacl_version}"

    runtimeOnly "org.antlr:antlr4-runtime:4.11.1"
    runtimeOnly "org.quiltmc.parsers:gson:0.2.1"
    runtimeOnly "io.github.douira:glsl-transformer:2.0.0-pre13"
    runtimeOnly "org.anarres:jcpp:1.4.14"

    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation project(":common")
}

loom {
    if (project(":common").file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(project(":common").file("src/main/resources/${mod_id}.accesswidener"))
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}
