plugins {
    id 'fabric-loom' version '1.13.6' apply(false)
    id 'net.neoforged.moddev' version '2.0.141' apply(false)
}

def getAppVersion = { ->
    try {
        def result = providers.exec {
            commandLine 'git', 'tag', '--points-at', 'HEAD'
        }
        def tag = result.standardOutput.asText.get().trim()
        if (tag.isEmpty()) return "0.0.0-SNAPSHOT"
        return tag.split('\\+')[0]
    } catch (Exception e) {
        println "Warning: ${e.message}, is git installed?"
        return "0.0.0-DEV"
    }
} as Object

allprojects {
    version = getAppVersion()
}
